/***********************************************************************************************************************
 *  $Header: svn://aldapp07.icgeu.com/HengProcDB/DB-abstraction-Layer/DBAL/src/dbalTest.c 465 2023-03-29 15:30:28Z fabian.brandauer $
 *  $Company: (c) Hengstler GmbH 2023 $
 **********************************************************************************************************************/
//https://docs.microsoft.com/en-us/dotnet/framework/interop/identifying-functions-in-dlls

#include <Windows.h>

#define DLL_INIT 1
#include <dbal.h>
#include <error.h>
#include <conio.h>
#include <stdio.h>
#include <station_1.h>

int retVal_l = 0;

int main ( void )
{
    // DBAL test procedure:
    // 
    // test prerequisites: 
    // - orders and products (barcode) are already known to DB
    // - dbal_attributes.h (generated by py script) used
    // 1. Announce product at first station
    // 2. add attribute
    // 3. verify if attribute has passed
    // repeat step 2 until all attributes
    // 4. wrap_up
    // 5. go to next station and repeat from step 1



    db_conf_t db_conf = { "test", "1234","localhost","root" };
    db_attr_t up_attr = { "12345678", LATHE_DISC_THICK, "1", "82 00 00 00 80 00","200","0",1,22,"dal.txt" };

    db_init ( &db_conf );

    update_attribute ( &up_attr );

    db_close ();

    return 0;
}
